const binary=[['Yes',1],['No',0]];
const fields=[['age_group','Age group',['18–24','25–29','30–34','35–39','40–44','45–49','50–54','55–59','60–64','65–69','70–74','75–79','80+'].map((x,i)=>[x,i+1])],['sex','Sex',[['Male',1],['Female',2]]],['bmi','Body Mass Index (BMI)',null],['general_health','General health',['Excellent','Very good','Good','Fair','Poor'].map((x,i)=>[x,i+1])],['physical_activity','Physical activity in the past 30 days',binary],['smoking_status','Smoking status',[['Current smoker — every day',1],['Current smoker — some days',2],['Former smoker',3],['Fewer than 100 cigarettes lifetime',4]]],['diabetes','Diabetes',[['Yes',1],['Only during pregnancy',2],['No',3],['Prediabetes / borderline',4]]],['stroke_history','Stroke history',binary],['kidney_disease','Kidney disease',binary],['asthma','Ever told you had asthma?',binary],['difficulty_walking','Difficulty walking or climbing stairs',binary],['high_cholesterol','Ever told you had high cholesterol?',binary],['high_blood_pressure','High blood pressure',binary],['alcohol_use','Alcohol use in the past 30 days',binary]];
const thresholds=['research_balanced','high_sensitivity_80','high_sensitivity_90','youden','conventional_050'];
const low={age_group:1,sex:2,bmi:22,general_health:1,physical_activity:1,smoking_status:4,diabetes:3,stroke_history:0,kidney_disease:0,asthma:0,difficulty_walking:0,high_cholesterol:0,high_blood_pressure:0,alcohol_use:0};
const high={age_group:11,sex:1,bmi:34,general_health:5,physical_activity:0,smoking_status:1,diabetes:1,stroke_history:1,kidney_disease:1,asthma:1,difficulty_walking:1,high_cholesterol:1,high_blood_pressure:1,alcohol_use:0};
const presets={'Young healthy profile':low,'Middle-age mixed profile':{...low,age_group:7,bmi:28.5,general_health:3,smoking_status:3,high_cholesterol:1},'Older high-association profile':high,'Missing-data profile':Object.fromEntries(fields.map(([k])=>[k,null])),'BMI missing':{...low,bmi:null},'Smoking missing':{...low,smoking_status:null},'High cholesterol missing':{...low,high_cholesterol:null},'Multiple values missing':{...low,bmi:null,smoking_status:null,high_cholesterol:null}};
const $=id=>document.getElementById(id),percent=x=>(x*100).toFixed(1)+'%',classification=x=>x==='elevated_model_association'?'Elevated model association':'Lower model association';
function option(label,value){const o=document.createElement('option');o.textContent=label;o.value=value;return o;}
function profile(){return Object.fromEntries(fields.map(([k])=>[k,$(k).value===''?null:Number($(k).value)]));}
function errorMessage(data){const e=data?.error;return e?.message?e.message+(e.details?.length?'\n'+e.details.map(d=>d.location.filter(x=>!['body','profile'].includes(x)).map(x=>fields.find(f=>f[0]===x)?.[1]??x).join(' / ')+': '+d.message).join('\n'):''):'The API could not process this request.';}
async function predict(p,t,fetcher=fetch){const r=await fetcher('/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:p,threshold_profile:t})});const data=await r.json();if(!r.ok){const e=new Error(errorMessage(data));e.data=data;throw e;}return data;}
function csv(rows){return rows.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');}
let current=null,baseline=null,records=[],revision=0;
function invalidate(){revision++;current=null;$('score').textContent='—';$('classification').textContent='Analyze to refresh results.';$('policy').textContent='';$('qa-result').textContent='';$('raw').textContent='';$('error').textContent='';$('comparison').textContent='';}
function populate(p){fields.forEach(([k])=>$(k).value=p[k]??'');invalidate();}
function show(data,p){current={data,profile:p};$('score').textContent=percent(data.profile_score);$('classification').textContent=classification(data.classification);$('version').textContent='Model version: '+data.model_version;$('policy').textContent='Research threshold: '+data.threshold;$('qa-result').textContent=`Threshold profile: ${data.threshold_profile} · Threshold: ${data.threshold} · Profile score: ${data.profile_score} · Classification: ${classification(data.classification)}`;$('raw').textContent=JSON.stringify(data,null,2);}
function initialize(){
 fields.forEach(([k,label,options])=>{const l=document.createElement('label');l.textContent=label;const input=document.createElement(options?'select':'input');input.id=k;input.name=k;if(options){input.append(option('Unknown',''));options.forEach(([a,b])=>input.append(option(a,b)));}else{input.type='number';input.min=12;input.max=99.99;input.step='any';input.placeholder='12–99.99; blank = unknown';}input.oninput=invalidate;l.append(input);$('fields').append(l);$('compare-field').append(option(label,k));});
 thresholds.forEach(t=>$('threshold').append(option(t,t)));Object.keys(presets).forEach(p=>$('preset').append(option(p,p)));$('threshold').onchange=invalidate;$('preset').onchange=()=>{if(presets[$('preset').value]){populate(presets[$('preset').value]);$('name').value=$('preset').value;}};$('clear').onclick=()=>populate({});$('raw-toggle').onchange=()=>$('raw').hidden=!$('raw-toggle').checked;
 $('form').onsubmit=async e=>{e.preventDefault();if(!$('form').reportValidity())return;invalidate();const p=profile(),t=$('threshold').value,sentRevision=revision;$('submit').disabled=true;$('submit').textContent='Analyzing…';try{const data=await predict(p,t);if(revision===sentRevision)show(data,p);}catch(err){if(revision===sentRevision){$('error').textContent=err.data?err.message:'Cannot reach the local API. Check that python -m api is running.';if(err.data)$('raw').textContent=JSON.stringify(err.data,null,2);}}finally{$('submit').disabled=false;$('submit').textContent='Analyze Profile';}};
 $('baseline').onclick=()=>{if(!current){$('comparison').textContent='Analyze the baseline first.';return;}baseline=structuredClone(current);$('comparison').textContent='Baseline captured. Modify one selected field.';};
 $('restore-baseline').onclick=()=>{if(baseline){populate(baseline.profile);$('threshold').value=baseline.data.threshold_profile;$('comparison').textContent='Baseline duplicated into the form.';}else $('comparison').textContent='Capture a baseline first.';};
 $('compare').onclick=async()=>{if(!baseline){$('comparison').textContent='Capture a baseline first.';return;}const original=structuredClone(baseline),p=profile(),sentRevision=revision,changed=fields.filter(([k])=>p[k]!==original.profile[k]);if(changed.length!==1||changed[0][0]!==$('compare-field').value){$('comparison').textContent='Change exactly the selected field from the baseline.';return;}if(!$('form').reportValidity())return;$('compare').disabled=true;try{const r=await predict(p,original.data.threshold_profile);if(revision===sentRevision)$('comparison').textContent=`Original score: ${percent(original.data.profile_score)} · Modified score: ${percent(r.profile_score)} · Absolute score difference: ${(Math.abs(r.profile_score-original.data.profile_score)*100).toFixed(3)} percentage points`;}catch(e){$('comparison').textContent=e.message;}finally{$('compare').disabled=false;}};
 $('invalid-example').onclick=async()=>{invalidate();const sentRevision=revision;$('invalid-example').disabled=true;try{await predict({...low,bmi:100},$('threshold').value);$('error').textContent='REVIEW: the invalid BMI example was unexpectedly accepted.';}catch(e){if(revision===sentRevision){$('error').textContent=e.data?'Expected QA validation error: '+e.message:'Cannot reach the local API.';if(e.data)$('raw').textContent=JSON.stringify(e.data,null,2);}}finally{$('invalid-example').disabled=false;}};
 try{records=JSON.parse(localStorage.getItem('cardiorisk-qa')||'[]');if(!Array.isArray(records))records=[];}catch{records=[];}$('records').textContent=JSON.stringify(records,null,2);
 $('record').onclick=()=>{if(!current){$('saved').textContent='Analyze the current profile first.';return;}records.push({test_id:$('test-id').value,profile_name:$('name').value,expected_qualitative_behavior:$('expected').value,actual_score:current.data.profile_score,actual_classification:classification(current.data.classification),threshold_profile:current.data.threshold_profile,status:$('status').value,notes:$('notes').value});try{localStorage.setItem('cardiorisk-qa',JSON.stringify(records));$('saved').textContent=`Saved ${records.length} local records.`;}catch{$('saved').textContent='Storage unavailable; export records now.';}$('records').textContent=JSON.stringify(records,null,2);};
 $('export').onclick=()=>{const keys=['test_id','profile_name','expected_qualitative_behavior','actual_score','actual_classification','threshold_profile','status','notes'],safe=v=>/^[=+\-@\t\r]/.test(String(v))?"'"+v:v;const url=URL.createObjectURL(new Blob([csv([keys,...records.map(r=>keys.map(k=>safe(r[k])))])],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='manual_model_qa.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('clear-records').onclick=()=>{records=[];localStorage.removeItem('cardiorisk-qa');$('records').textContent='[]';$('saved').textContent='Local QA records cleared.';};
}
if(typeof document!=='undefined')initialize();
if(typeof module!=='undefined')module.exports={fields,thresholds,presets,predict,errorMessage,csv,classification,profile};
